### ISSUE TITLE
Color should coordinate with the item instead of the action.

### ISSUE THREAD

**Issue by naknode** [Navarra/game#17]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Color coordinates with the action being taken.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Color should coordinate with the item instead of the action.

This would better distinguish the impact a player makes when an action takes place. When we right-click we already know what we're looking for so we want to find it quick in the menu. If we have two colors, like 'Take Bronze Sword' and 'Examine Bronze Sword', it can confuse people. If the `Bronze Sword` is the same color for whatever action acted upon it, it would be better, I believe.

As it stands this is how it is:
<img width="454" alt="captura de pantalla 2018-01-21 a las 9 58 15 pm" src="https://user-images.githubusercontent.com/616320/35204820-42c4304e-fef6-11e7-8cec-51a60ae346bf.png">

https://github.com/Navarra/game/blob/1f0a921605bba79f5234d9718a4c0521d291f788/src/core/player/actions.js#L25-L29

Which, in retrospect, is a bit confusing because it makes me think there are two different items at a cursory glance.

I think a better idea would be to group the items to have their own distinct (bright) color so we know what to look out for. For example:

```
Items: orange
NPCs: yellow
Players: white
(and so on)
```

**Comment by naknode** [comment]
Hi @dathappysheep! Glad to see you 'round these parts.

That is something left to semantics, whether to put this config in the `config.js` file or to put as `json` in that file on the client side.

I'd say the colors could be in the `config.js` from the client-side.

**Comment by dathappysheep** [comment]
Pull Request #20

**Comment by naknode** [comment]
Thank you for your help @dathappysheep. Will be closing this issue now that it's fixed.
